Repository konstellation-io/krt, pull requests merged in 2024-02, with the labels that each got.

#33 feat: add node selectors to processes
  internal/kubeutil/validations.go
  internal/kubeutil/validations_test.go
  pkg/krt/krt.go
  pkg/krt/krt_builder_test.go
  pkg/krt/process_builder_test.go
  pkg/krt/validations_process.go
  pkg/krt/validations_process_test.go
Labels: size/m

#34 merge develop into main
  internal/kubeutil/validations.go
  internal/kubeutil/validations_test.go
  pkg/krt/krt.go
  pkg/krt/krt_builder_test.go
  pkg/krt/process_builder_test.go
  pkg/krt/validations_process.go
  pkg/krt/validations_process_test.go
Labels: size/m

#36 ci: automate go release
  .github/workflows/test-release.yaml
Labels: size/s

#38 fix: improve readme
  README.md
Labels: size/xs

#39 ci: fix release job to use nyx
  .github/workflows/test-release.yaml
  .gitignore
  .nyx.yaml
  CHANGELOG.tpl
Labels: size/m

#41 feat: update go version to 1.22
  .github/workflows/test-release.yaml
  go.mod
  go.sum
Labels: size/s
